# Generated by Django 4.1.7 on 2023-03-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_veichledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='veichledetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
