# Generated by Django 4.1.7 on 2023-03-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_veichledetails_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VeichleDetails',
        ),
    ]
